version: '3.8'

services:
  app:
    build:
      context: ./app
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./app:/app  # This mounts the app directory in your host to the container
